version: '3.9'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - $DB_NAME:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: six-cities_mongo_express
    ports:
      - $DB_UI_PORT:$DB_UI_PORT
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_UI_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_UI_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$DB_USER:$DB_PASSWORD@db:$DB_PORT/

volumes:
  six-cities_data:
